version: 2.1

jobs:
  linting-html:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo npm install 
            sudo npm install -g htmlhint
      - run:
          name: HTML Linting
          command: sudo npm run lint:html

  
workflows:
  default:
    jobs:
      - linting-html
     