version: 2.1

jobs:
  linting-html:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      # - run:
      #     name: HTML Linting
      #     command: npm run lint:html

  
workflows:
  default:
    jobs:
      - linting-html
     