version: 2.1

jobs:
  linting-html:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo npm install 
            sudo npm install -g htmlhint
      - run:
          name: HTML Linting
          command: sudo npm run lint:html
  build-upload-image:
    docker:
      - image: circleci/node:14 
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: sudo docker build -t remambian/udablueimage:latest .
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push to Docker Hub
          command: docker push remambian/capstoneblue:latest

  
workflows:
  default:
    jobs:
      - linting-html
      - build-upload-image
     