version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.2.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  linting-html:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo npm install 
            sudo npm install -g htmlhint
      - run:
          name: HTML Linting
          command: sudo npm run lint:html
  build-upload-image:
    docker:
      - image: circleci/node:14 
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: sudo docker build -t remambian/capstoneblue:latest .
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push to Docker Hub
          command: docker push remambian/capstoneblue:latest

  deploy-infrastructure:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - run:
          name: Install eksctl
          command: |
            sudo curl --silent --location -o /usr/local/bin/eksctl "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64"
            sudo chmod +x /usr/local/bin/eksctl
      - aws-eks/install-aws-iam-authenticator:
          release-tag: ""
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
          node-type: t2.small
          nodes-max: 2
          ssh-access: false
          ssh-public-key: ""

workflows:
  default:
    jobs:
      - linting-html        
      - build-upload-image:
          requires:
            - linting-html
      - deploy-infrastructure:
          cluster-name: capstone-project-cluster
          requires:
            - build-upload-image      
