version: 2.1

jobs:
  linting-html:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo npm install 
            sudo npm install -g htmlhint
      - run:
          name: HTML Linting
          command: sudo npm run lint:html
  build-upload-image:
    docker:
      - image: circleci/node:14 
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: sudo docker build -t remambian/capstoneblue:latest .
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push to Docker Hub
          command: docker push remambian/capstoneblue:latest
 create-deployment:
  executor: aws-eks/python3
  parameters:
    cluster-name:
      description: | 
        Name of the EKS cluster
      type: string
  steps:
    - checkout
    - aws-eks/update-kubeconfig-with-authenticator:
      cluster-name: << parameters.cluster-name >>
      install-kubectl: true
    - kubernetes/create-or-update-resource:
      get-rollout-status: true
      resource-file-path: deployment.json
      resource-name: deployment/blue


workflows:
  default:
    jobs:
      - linting-html
      - build-upload-image
      - create-deployment
     